language: r
sudo: required
cran: http://cran.rstudio.com
dist: trusty
cache: packages
warnings_are_errors: true

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

notifications:
  email:
    on_success: change
    on_failure: change
