language: r
sudo: required
cran: http://cran.rstudio.com
dist: trusty
cache: packages
warnings_are_errors: false

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

matrix:
  include:
    - r: release
      r_github_packages: adamdsmith/itistools
    - r: devel
      r_github_packages: adamdsmith/itistools
    - r: oldrel
      r_github_packages: adamdsmith/itistools

notifications:
  email:
    on_success: change
    on_failure: change
